---
title: "(3) Uploading and Combining Death Data"
author: "Anna Stouffer"
date: "2024-05-22"
output: html_document
---

################ THIS FILE HAS BEEN REPLACED WITH clean_opiod_death_data.R  #######################

---
title: "NC Death Analysis"
author: "annastouffer"
date: "2023-10-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# preprocess raw data
source("clean_opiod_death_data.R")
```

```{r}
write_opiod_death_tables()
```

```{r}
# load data
all_deaths <- read.csv(file.path(DEATH_DATA_DIR, OPIOD_DEATH_DIR, "all_death_data_2022.csv"))
death_data_1999_2013 <- read.csv(file.path(DEATH_DATA_DIR, OPIOD_DEATH_DIR, "nc_opiod_deaths_1999_2013.csv"))
death_data_2014_2022 <- read.csv(file.path(DEATH_DATA_DIR, OPIOD_DEATH_DIR, "nc_opiod_deaths_2014_2022.csv"))
```

```{r}
# population data
# from https://www.osbm.nc.gov/facts-figures/population-demographics/state-demographer/county-population-estimates/county-population-estimates

population_data <- read.csv(file.path(DEATH_DATA_DIR, "NCprojectionsbyage2022.csv"))

result <- population_data %>%
  group_by(year, county, fips) %>%
  summarize(total_population = sum(total))

write.csv(result, file.path(DEATH_DATA_DIR, "population_per_county_per_year.csv"), row.names = FALSE)

# Calculate the total population for each year and county
```

```{r}
# trying ACS...don't think this method will work

# Define your API key (you need to get your own API key from the U.S. Census Bureau)
census_api_key("d2bf4e425f145a0f6c90f045163548e4a295b648", install = TRUE, overwrite = TRUE)

# Specify the variables you want (P001001 is the code for total population)
variables <- c("P001001")

county_map <- get_decennial(
  geography = "county",
  variables = c("Total_pop" = "P001001"),
  year = 2010,
  output = "wide",
  geometry = TRUE,
  state = 37
)

county_map <- counties(state = "NC")
```


```{r}
# trends for each county

# Create a summary table with death counts per year and county
death_trends_2014_data <- all_deaths %>%
  group_by(Year = year(deathdate), county, GEOID) %>%
  summarise(Deaths = n())

death_trends_2014_data <- death_trends_2014_data %>%
  left_join(county_map %>% select(GEOID, Total_pop), by = "GEOID")

death_trends_2014_data$death_rate <- (death_trends_2014_data$Deaths / death_trends_2014_data$Total_pop) * 100000

ggplot(death_trends_2014_data, aes(x = Year, y = death_rate, color = county)) +
  geom_line() +
  labs(
    title = "Death Rate Trends per County (2014-2021)",
    x = "Year",
    y = "Number of Deaths"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") # Adjust legend position as needed


ggplot(death_trends_2014_data, aes(x = Year, y = death_rate, color = county)) +
  geom_line() +
  labs(
    title = "Death Rate Trends per County (2014-2021)",
    x = "Year",
    y = "Number of Deaths"
  ) +
  theme_minimal() +
  guides(color = "none") # Hide the legend


plot_ly(data = death_trends_2014_data, x = ~Year, y = ~death_rate, color = ~county) %>%
  add_lines() %>%
  layout(
    title = "Death Rate Trends by County (2014-2021)",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Number of Deaths"),
    showlegend = TRUE
  ) # Hide the legend
```


```{r}
death_trends_year <- all_deaths %>%
  group_by(Year = year(deathdate)) %>%
  summarise(Deaths = n())

combined_data <- bind_rows(death_trends_year, death_trends_year_1999)

ggplot(death_trends_year, aes(x = Year, y = Deaths)) +
  geom_line() +
  labs(
    title = "Number of Opioid Overdose Deaths in NC (1999-2021)",
    x = "Year",
    y = "Number of Deaths"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") # Adjust l
```



############# PLOTS ###################

```{r}
# visualizing county representiation 2014 - 2021

# only 51 counties are represented as containing overdose deaths between 2014 and 2021
print(length(unique(death_data$county)))

# counting deaths per county
county_counts <- table(all_deaths$county)

# creating a dataframe of death counts per county
county_counts_df <- data.frame(County = names(county_counts), Count = as.numeric(county_counts))

ggplot(county_counts_df, aes(x = reorder(County, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "County", y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("County Representation in Data")
```

```{r}
# visualizing county representiation 1999 - 2013

# only 51 counties are represented as containing overdose deaths between 2014 and 2021
print(length(unique(death_data_1999$county)))

# counting deaths per county
county_counts <- table(death_data_1999$county)

# creating a dataframe of death counts per county
county_counts_df <- data.frame(County = names(county_counts), Count = as.numeric(county_counts))

ggplot(county_counts_df, aes(x = reorder(County, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "County", y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("County Representation in Data")
```

```{r}
# plotting death on a map of north carolina 2014 - 2021

# getting the NC shapefile
get_acs_decennial <- function(geography) {
  acs_year <- get_decennial(
    geography = geography,
    variables = c(
      "Total_pop" = "P001001",
      "White" = "P005003",
      "Black" = "P005004",
      "Asian" = "P005006",
      "Hispanic" = "P005010"
    ),
    year = 2010,
    output = "wide",
    geometry = TRUE,
    state = 37
  ) %>%
    st_transform(crs = st_crs(4326)) %>%
    filter(!st_is_empty(.)) %>%
    mutate(Other = Total_pop - White - Black - Asian - Hispanic)
  return(acs_year)
}

county_map <- get_acs_decennial("county")

# getting rid of the demographics columns here
county_map <- subset(county_map, select = -c(Total_pop, White, Black, Asian, Hispanic, Other))

# merging with death data based on GEOID
nc_counties <- merge(county_map, all_deaths, by = "GEOID")

# calculating the row counts for each county
county_row_counts <- as.data.frame(table(nc_counties$GEOID))

# merging the row counts with the county geometries
nc_counties <- merge(nc_counties, county_row_counts, by.x = "GEOID", by.y = "Var1", all.x = TRUE)

# plot
ggplot() +
  geom_sf(data = nc_counties, aes(fill = Freq), color = "white") +
  scale_fill_gradient(low = "lightblue", high = "darkblue", name = "Row Count") +
  labs(title = "North Carolina Counties by Row Count") +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
# Convert deathdate to year
nc_counties$year <- format(nc_counties$deathdate, "%Y")


plot_wave <- function(data, start, end, title) {
  to_plot <- filter(data, year >= start & year < end)

  ggplot() +
    geom_sf(data = to_plot, aes(fill = Freq), color = "white") +
    scale_fill_gradient(low = "lightblue", high = "darkblue", name = "Row Count") +
    labs(title = title) +
    theme_minimal() +
    theme(legend.position = "bottom")
}

plot_2000_2021 <- plot_wave(nc_counties, 2000, 2021, "Overall (2000-2021)")
plot_2000_2010 <- plot_wave(nc_counties, 2000, 2010, "Wave 1 (2000-2010)")
plot_2010_2013 <- plot_wave(nc_counties, 2010, 2013, "Wave 2 (2010-2013)")
plot_2013_2018 <- plot_wave(nc_counties, 2013, 2018, "Wave 3 (2013-2018)")
plot_2018_2021 <- plot_wave(nc_counties, 2018, 2021, "Wave 4 (2018-2021)")

# Arrange plots horizontally
all_plots <- plot_2000_2021 + plot_2000_2010 + plot_2010_2013 + plot_2013_2018 + plot_2018_2021

# Print the combined plot
all_plots
```

```{r}
# plotting death rate on a map of north carolina 2014 - 2021

# getting the NC shapefile
get_acs_decennial <- function(geography) {
  acs_year <- get_decennial(
    geography = geography,
    variables = c(
      "Total_pop" = "P001001",
      "White" = "P005003",
      "Black" = "P005004",
      "Asian" = "P005006",
      "Hispanic" = "P005010"
    ),
    year = 2010,
    output = "wide",
    geometry = TRUE,
    state = 37
  ) %>%
    st_transform(crs = st_crs(4326)) %>%
    filter(!st_is_empty(.)) %>%
    mutate(Other = Total_pop - White - Black - Asian - Hispanic)
  return(acs_year)
}

county_map <- get_acs_decennial("county")

# getting rid of the demographics columns here
county_map <- subset(county_map, select = -c(White, Black, Asian, Hispanic, Other))

# merging with death data based on GEOID
nc_counties <- merge(county_map, death_data, by = "GEOID")

# calculating the row counts for each county
county_row_counts <- as.data.frame(table(nc_counties$GEOID))

county_row_counts$GEOID <- county_row_counts$Var1

county_row_counts <- county_row_counts %>%
  left_join(county_map %>% select(GEOID, Total_pop), by = "GEOID")

county_row_counts$death_rate <- (county_row_counts$Freq / county_row_counts$Total_pop) * 100000

nc_counties <- left_join(nc_counties, county_row_counts, by = "GEOID")

# plot
ggplot() +
  geom_sf(data = nc_counties, aes(fill = death_rate), color = "white") +
  scale_fill_gradient(low = "lightblue", high = "darkblue", name = "Row Count") +
  labs(title = "Overdose Death Rate per 100,000 People 2014 - 2021 Aggregate") +
  theme_minimal() +
  theme(legend.position = "bottom")
```


```{r}
# plotting death rate on a map of north carolina 2014 - 2021 LOOP

# getting the NC shapefile
get_acs_decennial <- function(geography) {
  acs_year <- get_decennial(
    geography = geography,
    variables = c(
      "Total_pop" = "P001001",
      "White" = "P005003",
      "Black" = "P005004",
      "Asian" = "P005006",
      "Hispanic" = "P005010"
    ),
    year = 2010,
    output = "wide",
    geometry = TRUE,
    state = 37
  ) %>%
    st_transform(crs = st_crs(4326)) %>%
    filter(!st_is_empty(.)) %>%
    mutate(Other = Total_pop - White - Black - Asian - Hispanic)
  return(acs_year)
}

county_map <- get_acs_decennial("county")


# getting rid of the demographics columns here
county_map <- subset(county_map, select = -c(White, Black, Asian, Hispanic, Other))


for (year in 2014:2021) {
  death_data_year <- subset(death_data, year(death_data$DTHDATE) == year)
  # merging with death data based on GEOID
  nc_counties <- merge(county_map, death_data_year, by = "GEOID")

  # calculating the row counts for each county
  county_row_counts <- as.data.frame(table(nc_counties$GEOID))

  county_row_counts$GEOID <- county_row_counts$Var1

  county_row_counts <- county_row_counts %>%
    left_join(county_map %>% select(GEOID, Total_pop), by = "GEOID")

  county_row_counts$death_rate <- (county_row_counts$Freq / county_row_counts$Total_pop) * 100000

  nc_counties <- left_join(nc_counties, county_row_counts, by = "GEOID")

  # plot
  plot <- ggplot() +
    geom_sf(data = nc_counties, aes(fill = death_rate), color = "white") +
    scale_fill_gradient(low = "lightblue", high = "darkblue", name = "Row Count", limits = c(0, 100)) +
    labs(title = paste("Overdose Death Rate per 100,000 people", year)) +
    theme_minimal() +
    theme(legend.position = "bottom")

  # file_name <- paste("/Users/annastouffer/Documents/Yale/Thesis/Death Data/NC Death Rate Plots/plot_", year, ".png", sep = "")
  # ggsave(file_name, plot, width = 6, height = 4, dpi = 300)
  print(plot)
}
```

```{r}
# plotting death rate on a map of north carolina 1999 - 2013 LOOP

# getting the NC shapefile
get_acs_decennial <- function(geography) {
  acs_year <- get_decennial(
    geography = geography,
    variables = c(
      "Total_pop" = "P001001",
      "White" = "P005003",
      "Black" = "P005004",
      "Asian" = "P005006",
      "Hispanic" = "P005010"
    ),
    year = 2010,
    output = "wide",
    geometry = TRUE,
    state = 37
  ) %>%
    st_transform(crs = st_crs(4326)) %>%
    filter(!st_is_empty(.)) %>%
    mutate(Other = Total_pop - White - Black - Asian - Hispanic)
  return(acs_year)
}

county_map <- get_acs_decennial("county")


# getting rid of the demographics columns here
county_map <- subset(county_map, select = -c(White, Black, Asian, Hispanic, Other))


for (year in 1999:2013) {
  death_data_year <- subset(death_data_1999, year(death_data_1999$DTHDATE) == year)

  # merging with death data based on GEOID
  nc_counties <- merge(county_map, death_data_year, by = "GEOID")

  # calculating the row counts for each county
  county_row_counts <- as.data.frame(table(nc_counties$GEOID))

  county_row_counts$GEOID <- county_row_counts$Var1

  county_row_counts <- county_row_counts %>%
    left_join(county_map %>% select(GEOID, Total_pop), by = "GEOID")

  county_row_counts$death_rate <- (county_row_counts$Freq / county_row_counts$Total_pop) * 100000

  nc_counties <- left_join(nc_counties, county_row_counts, by = "GEOID")

  # plot
  plot <- ggplot() +
    geom_sf(data = nc_counties, aes(fill = death_rate), color = "white") +
    scale_fill_gradient(low = "lightblue", high = "darkblue", name = "Row Count", limits = c(0, 100)) +
    labs(title = paste("Overdose Death Rate per 100,000 people", year)) +
    theme_minimal() +
    theme(legend.position = "bottom")

  # file_name <- paste("/Users/annastouffer/Documents/Yale/Thesis/Death Data/NC Death Rate Plots/plot_", year, ".png", sep = "")
  # ggsave(file_name, plot, width = 6, height = 4, dpi = 300)
  print(plot)
}
```
